### ISSUE TITLE
in-game chat embeds do not show server version when the server is empty

### ISSUE THREAD

**Issue by DorkOrc** [Tec-Tonic/PandamiumBot#4]
As you can see in the image below, the server version information is missing from the embed when the server is empty.
Offline:
![image](https://github.com/Tec-Tonic/PandamiumBot/assets/16517352/9c1d7c9a-b1ba-4834-8f2a-6dc0b60520be)
Online:
![image](https://github.com/Tec-Tonic/PandamiumBot/assets/16517352/2e85b615-db7b-44e1-8b0c-fd97783c5127)

**Comment by Tec-Tonic** [comment]
I will add that later today.
